<?php

namespace Sorethea\FilamentModule\Commands;

use Nwidart\Modules\Commands\ModuleMakeCommand as Command;

class ModuleMakeCommand extends Command
{
    protected $signature = 'module:make-filament-module';

    protected $description = 'Command description';

    public function handle(): int
    {
        return parent::handle(); // TODO: Change the autogenerated stub
    }

}
